
package lib.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogServiceImplService", targetNamespace = "http://service.soap.project.com/", wsdlLocation = "http://localhost:8090/log?wsdl")
public class LogServiceImplService
    extends Service
{

    private final static URL LOGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LOGSERVICEIMPLSERVICE_QNAME = new QName("http://service.soap.project.com/", "LogServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/log?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LOGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LogServiceImplService() {
        super(__getWsdlLocation(), LOGSERVICEIMPLSERVICE_QNAME);
    }

    public LogServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGSERVICEIMPLSERVICE_QNAME, features);
    }

    public LogServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LOGSERVICEIMPLSERVICE_QNAME);
    }

    public LogServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGSERVICEIMPLSERVICE_QNAME, features);
    }

    public LogServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogService
     */
    @WebEndpoint(name = "LogServiceImplPort")
    public LogService getLogServiceImplPort() {
        return super.getPort(new QName("http://service.soap.project.com/", "LogServiceImplPort"), LogService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogService
     */
    @WebEndpoint(name = "LogServiceImplPort")
    public LogService getLogServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.project.com/", "LogServiceImplPort"), LogService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LOGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LOGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
