
package lib.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogService", targetNamespace = "http://service.soap.project.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<lib.client.LogEntry>
     * @throws RepException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLogs", targetNamespace = "http://service.soap.project.com/", className = "lib.client.GetLogs")
    @ResponseWrapper(localName = "getLogsResponse", targetNamespace = "http://service.soap.project.com/", className = "lib.client.GetLogsResponse")
    @Action(input = "http://service.soap.project.com/LogService/getLogsRequest", output = "http://service.soap.project.com/LogService/getLogsResponse", fault = {
        @FaultAction(className = RepException_Exception.class, value = "http://service.soap.project.com/LogService/getLogs/Fault/RepException")
    })
    public List<LogEntry> getLogs(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws RepException_Exception
    ;

    /**
     * 
     * @throws RepException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "clearLogs", targetNamespace = "http://service.soap.project.com/", className = "lib.client.ClearLogs")
    @ResponseWrapper(localName = "clearLogsResponse", targetNamespace = "http://service.soap.project.com/", className = "lib.client.ClearLogsResponse")
    @Action(input = "http://service.soap.project.com/LogService/clearLogsRequest", output = "http://service.soap.project.com/LogService/clearLogsResponse", fault = {
        @FaultAction(className = RepException_Exception.class, value = "http://service.soap.project.com/LogService/clearLogs/Fault/RepException")
    })
    public void clearLogs()
        throws RepException_Exception
    ;

}
